//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinestarDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Show()
        {
            this.ShowSeatLayouts = new HashSet<ShowSeatLayout>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ShowId { get; set; }
        public System.DateTime ShowDate { get; set; }
        public System.TimeSpan ShowTime { get; set; }
        public int Price { get; set; }
        public int ScreenId { get; set; }
        public int MovieId { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Screen Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowSeatLayout> ShowSeatLayouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
