//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinestarDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticketid { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int NoOfTickets { get; set; }
        public int ViewersId { get; set; }
        public int ShowId { get; set; }
        public int MovieId { get; set; }
        public int Price { get; set; }
        public string Seats { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Show Show { get; set; }
        public virtual ViewerProfile ViewerProfile { get; set; }
    }
}
